name:         "westgatecyber"
host:         "westgatecyber.com"
url: 			    "https://westgatecyber.com/"
baseurl: 		  "/"

plugins:
 - jekyll-redirect-from
 - jekyll-sitemap
 
sass:
 sass_dir: _sass
 style: :compressed
